name: Laravel


on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into VPS and pull
      run: |
        ssh -i /path/to/your/private/ssh/key user@your-vps-ip 'cd /home/ovispa.app && git pull'
    
